name: StaffLogs
version: '1.0-SNAPSHOT'
main: pepino.staffLogs.StaffLogs
api-version: '1.21'
load: STARTUP
authors: [ TheNailpepino ]
description: This plugin will send a message to a webhook when commands commonly executed by staff are executed. (/tp, /gamemode, and /ban)
